### PR TITLE
Html5 port of Hiversaires

### PR DESCRIPTION
**Pull request by Rezmason**
Hey, Sea Peoples!

About three weeks ago, I decided to look at the Hiversaires code, to see if it could be added to your itch.io collection. It wasn't all that hard to port, actually, but I've done a bunch of cleanup besides that. It was a bit of a whirlwind, let me see if I can list the changes:

- The game's been divided into several manager classes and puzzle classes, as well as a data script that generates an immutable static world.
- The game's save state has been minimized considerably.
- There is a full walkthrough. Setting its speed to more than 200 Hz makes it sound like Oquonie's record player guy freestyling.
- There's a preliminary "cartographer" that maps the nodes and spits out an XGML file that yEd can read. At some point this could turn into a script to generate a PDF to sell alongside the game.
- Almost everything that could be a vector graphic is now an SVG asset.
- There are hand and fuse cursors. They're SVG, too. I did the best I could.
- The ghost is back, but appears in earlier than Act 5. That's partly because players enter and leave Act 5 as they complete the game. Ghosts are their own image billboard above the viewMain, so you won't have to flatten them again. They could even be separate assets, if you want.
- The credits are text, set to an open source DIN
- Entente's been rebuilt. Most nodes are the same, but a couple were reconstructed to make it feel more continuous.
- The UI elements are laid out statically, the only motion that ever really occurs is the quick shifting of viewMain during footsteps. UI layout is all percentage based.
- The main.js calculates how to display the game at 16:9, as tall as possible. If you move the game between screens, it'll resize for whichever screen it's on. This can all go away if we support other aspect ratios, but that's not my decision to make
- The node images have a very different naming scheme. I can use git to create a mapping from the old one to the new one, if we do any rerendering. (I stopped short of downloading the C4D trial.)
- Added keyboard control! Left and right keys turn left and right; the up key interacts with the puzzle in front of you, if there is one, but otherwise moves you forward. The down arrow key lets you step backwards, including passing through doors. Now that Entente's mechanics are door-based, rather than template-based, it's absolutely possible to ride the belly of the snake backwards— which sounds like a peyote trip.
- Like Oquonie and Verreciel, there is a hiversaires global object to facilitate debugging, but there's an alias called "hh", too.

There's plenty of stuff you've added to Oquonie and Verreciel that hasn't made it into Hiversaires. I also have my eye on our index.html pages, which are 90% script tags. As soon as Electron supports Chrome 61, we can try converting the JS files to ES6 modules (which Expo.io supports already), but that's not a priority. Also I imagine someone more familiar with CSS than me could assist in making the HUD aspect ratio independent.

That's all I can think of for now. This was fun, just like before! I'd never ported Objective-C code before, and the first time I ever encountered Entente was _in the HTML5 version_, by mistake. That was really magical. 😃 It was as if I'd built a machine from diagrams, and only discovered it had a hidden function after I was done building.

Let me know if you have any questions!

### CODE REVIEW

**Comment by Rezmason** [comment]
I forgot to mention one thing!

Node 60 in Antechannel links to node 56 in one direction, but in the other direction 56 links to 58, which links to 60. In other words, one Antechannel hallway is a little shorter in one direction than the other hallway.

It's probably a bug, but do we _want_ that fixed? Isn't the impossible geometry Hiversaires's aesthetic? It's up to you.

**Comment by neauoire** [comment]
Freakin' unbelievable.

**Comment by neauoire** [comment]
Give me a few days to play with this :) 
I am infinitely grateful, again.

**Comment by Rezmason** [comment]
Fun, worthwhile, reciprocative, puts smiles on cool people's faces. What can I say?

**Comment by neauoire** [comment]
I've started re-rendering the game, it's so good to know that this project will survive.
JS will outlive us all.

**Comment by Rezmason** [comment]
You know that's a really rare attitude. Like, after reading Ozymandias, how many people think, "Well yeah, but, maybe the ruins of civilizations in featureless wastelands are Turing complete"?

**Comment by Rezmason** [comment]
"Maybe in the last moment before heat death, a Boltzmann brain somewhere will stochastically think of us and relate to us" 😅

**Comment by Rezmason** [comment]
Just added this to the repo. Let me know if I can be of any further assistance: 

https://raw.githubusercontent.com/hundredrabbits/Hiversaires/67d69da314f86493bb4a8d91803331cc4ddb884b/graphics%20mapping.txt

**Pull request merged**
