### PR TITLE
Optimised all bitmap graphics

### PR DESCRIPTION
**Pull request by gingerbeardman**
I ran the PNG and JPG files through ImageOptim (lossless optimisation and metadata removal).
I then ran the JPG files though JPEGmini (lossy but unnoticeable optimisation).

On desktop the main gains were the JPG files which had approx 10MB of metadata! Another 10MB was saved through optimisation. Smaller gains on JPG for iOS due to smaller image sizes, but some savings on PNG meant that roughly equivalent savings as desktop. 

So, approx 40MB was saved across the whole project through this automatic process.

🏋️‍♀️

### CODE REVIEW

**Comment by Rezmason** [comment]
I'll leave this to @neauoire to merge. I think we'll need to optimize the graphics after every rerender to prevent the git history from getting filled with small iterations on large binary files.

We might want to look into npm packages we can install that perform image optimization for us, so that it's a part of the project.

**Comment by Rezmason** [comment]
@gingerbeardman In a separate branch off of master, can you try installing and running one of these, and comparing their output size/quality with your ImageOpim and JPEGmini output? Otherwise one of us could try it out.

https://www.npmjs.com/package/image-optimize
https://www.npmjs.com/package/imagemin

**Comment by Rezmason** [comment]
Also: I remember playing your game Wire Hang Redux! 😎👍

**Comment by neauoire** [comment]
Yeah, I agree with @Rezmason, I'd rather find a solution that does this programmatically. Otherwise, next time I render the world, it will re-overwrite them.

**Comment by gingerbeardman** [comment]
Agreed, I'll report back with some figures from image-optimize, imagemin, etc soon.

**Comment by neauoire** [comment]
Looking forward :) I think this would be a great addition!

**Comment by gingerbeardman** [comment]
desktop version, node-render folder

My approach: 46 MB
image-optimise: 60 MB
original: 68 MB

**Comment by neauoire** [comment]
So we save 8mb..? Not really worth to add an extra build process for that I suppose.

**Comment by gingerbeardman** [comment]
I'll do more investigation. I'm not yet convicted. 

That's 8MB off that one folder, but it's the folder with the most opportunity for saving.

**Comment by Rezmason** [comment]
In any case, as long as we mimic @gingerbeardman 's process whenever we rerender, we should be able to keep the sizes down.

We could also invent our own image format for games with small color palettes. 😜

**Comment by gingerbeardman** [comment]
There's a separate process for reducing the colours in a PNG 😮

**Pull request closed without merging**
